### ISSUE TITLE
Extending saga

### ISSUE THREAD

**Issue by floatdrop** [nomisRev/Saga#166]
Hi! 

Sometimes we need to attach additional steps to a `Saga` after we leave `SagaEffect` scope. For example we need something like this:

```kotlin
val ctxSaga = saga {
    // Do action one
}

// Some callstacks later...

with (ctxSaga) {
    // Do action two, but if it fails - please rollback action one
}
```

Am I missing some trick to do this or it just not implemented yet? And if so – would you consider PR for this?

Thanks for sharing this library!

**Comment by nomisRev** [comment]
Hey @floatdrop,

Thanks for taking an interest in this library ☺️

You can define Saga's separately, and compose them together inside the DSL.
Not actually happens until you call `transact`, so up until `transact` you can continue composing different saga's together using `bind` and `saga { }` blocks.

```kotlin
val orderSaga: Saga<Order> = saga(action = { createOrder() }, compensation = { ::deleteOrder })

val paymentSaga: Saga<Payment> = 
  saga(action = { createPayment(order) }, compensation = { ::deletePayment) })

val x: Saga<Unit> = saga {
  val order = orderSaga.bind()    
  val payment = paymentSaga.bind() 
  payment.awaitSuccess()
}

val moreSaga = saga {
  x.bind()
  x.bind()
}

moreSaga.transact()
```

I'm not entirely sure if this answers you question, if not can you please provide a more complete snippet including return types?

This data type has become part of `arrow-resilience` in 1.2.0-RC, https://arrow-kt.io/learn/resilience/saga/.
Are you open to relying on that in the future? It only relies on _core_ which will have a 400KB size in 2.0.0.
Otherwise I might consider pushing it down in a separate module on its own, or continue supporting this separate library.

**Comment by floatdrop** [comment]
Thanks for answer. I realise that in example missed key point – `transact` is in fact should be called and _then_ we can attach next steps to saga.

Suppose we have GraphQL handler (or sequence of HTTP middlewares) and do some actions for request on the way to response. We could create `Saga` at the top of the stack and attach steps to current saga as we go down through middlewares – so naturally on each step saga should be executed. After each step next middleware takes place and may (or may not) attach another step to current saga.

> This data type has become part of arrow-resilience in 1.2.0-RC, https://arrow-kt.io/learn/resilience/saga/.

Oh, that's cool – it definately should be mentioned in readme thou 😅

**Comment by nomisRev** [comment]
> Oh, that's cool – it definately should be mentioned in readme thou 😅

Yes, I was planning to do this when 1.2.0 (non-RC) is released.

**Comment by nomisRev** [comment]
Yes, exactly. You can also manually capture `this` and pass it as `SagaEffect` down to any nested code as a parameter in case you can not nest the DSLs.
